### ISSUE TITLE
Cannot open sample project

### ISSUE THREAD

**Issue by ipninichuck** [corneel/KafkaSampleProject#1]
Hello,

  I have purchased your plugin from the UE4 Marketplace but I am unable to open the sample project or use the third party dll's in the binaries folder in a project of my own. I am currently using UE4 4.22.2 on a Windows 10 64bit PC. So far when I attempt to start the project it begins to load but cannot use the dll's. This eventually causes the Unreal Editor to crash. I am attaching a screenshot showing the error being presented by windows and the crash report from UE4. Please help me figure out what I am doing wrong, I really need to use Kafka with UE4 for a project.

Thank you for your help
[KafkaSampleProject.log](https://github.com/corneel/KafkaSampleProject/files/3471035/KafkaSampleProject.log)
![Screenshot (7)](https://user-images.githubusercontent.com/26333671/62522299-40db8480-b7e6-11e9-99a9-7caa604276fa.png)

**Comment by corneel** [comment]
Hello,

The sample project contains the third party libraries that you need so you should not have an issue with that. I suspecft that you do not have git lfs installed.

Please follow these instructions and then check out the sample project again: https://git-lfs.github.com/

Let me know what is going on, I want to help you to be successful.

Thanks.
Corneel.

On Aug 6, 2019, at 3:05 AM, ipninichuck <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I have purchased your plugin from the UE4 Marketplace but I am unable to open the sample project or use the third party dll's in the binaries folder in a project of my own. I am currently using UE4 4.22.2 on a Windows 10 64bit PC. So far when I attempt to start the project it begins to load but cannot use the dll's. This eventually causes the Unreal Editor to crash. I am attaching a screenshot showing the error being presented by windows and the crash report from UE4. Please help me figure out what I am doing wrong, I really need to use Kafka with UE4 for a project.

Thank you for your help
KafkaSampleProject.log<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorneel%2FKafkaSampleProject%2Ffiles%2F3471035%2FKafkaSampleProject.log&data=02%7C01%7C%7Ca45632fb480b46800b6908d71a44dda6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637006755427208879&sdata=rnQ3mZnKck%2Bg8pwSP0%2BYY%2F34RoDuIy1xTOlM6dv6OJ4%3D&reserved=0>
[Screenshot (7)]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F26333671%2F62522299-40db8480-b7e6-11e9-99a9-7caa604276fa.png&data=02%7C01%7C%7Ca45632fb480b46800b6908d71a44dda6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637006755427228889&sdata=1AUb1t4lALEmBhIr0PikrIQdO%2FivgmnIgw2nenDBQtc%3D&reserved=0>

**Comment by ipninichuck** [comment]
Thank you,

  Once I used the application you linked the sample project properly downloaded the files. Thank you also for making such a fantastic plugin that enhances the abilities of UE4. I will definitely give you direct credit for making this use of Kafka possible.

Ivan Ninichuck

**Comment by corneel** [comment]
You are very welcome!

Thanks.
Corneel.

On Aug 7, 2019, at 3:49 AM, ipninichuck <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you,

Once I used the application you linked the sample project properly downloaded the files. Thank you also for making such a fantastic plugin that enhances the abilities of UE4. I will definitely give you direct credit for making this use of Kafka possible.

Ivan Ninichuck
